### ISSUE TITLE
Remove koij-tools.request (or make more generic?)

### ISSUE THREAD

**Issue by sthielen** [madewithkoji/koji-tools#1]
https://github.com/madewithkoji/koji-tools/blob/master/tools/request.js#L80

This is too prescriptive, especially the authorization stuff. If we can have a generic JSON request wrapper that would be awesome, but defining headers and keys like `isProtected` is too prescriptive

**Comment by jonesnxt** [comment]
got rid of the auth token stuff, it was just legacy from the origin request in koji_utilities, and cleaned it up a bit more
