### ISSUE TITLE
Bug in wrapConsole.js: `window.parent` is always truthy

### ISSUE THREAD

**Issue by mirismaili** [madewithkoji/koji-tools#23]
https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/tools/wrapConsole.js#L34-L38

From `if (window.parent)` seems the author wanted to sure the app (web page) is running in a container (not in the browser directly). If so, this is not the correct way. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/parent):

> **If a window does not have a parent, its parent property is a reference to itself.**

This means `window.parent` is always truthy whether the window has a parent or not. So the `if` statement filters nothing!

We can implement the same purpose as follows:

```js
if (window.parent !== window)
```

**Comment by sthielen** [comment]
`wrapConsole` was removed from this package and incorporated into Koji at a lower level
