### ISSUE TITLE
Bug in request.js: throws error in onFulfilled handler!

### ISSUE THREAD

**Issue by mirismaili** [madewithkoji/koji-tools#24]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Syntax) the first parameter of `then` function (of a `Promise`) is `onFulfilled` callback:

> `p.then(onFulfilled[, onRejected]);`

So below `throw` command will run when `json()` method **successfully resolved**:

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/tools/request.js#L22-L32

According to the same page 

> If a handler function [...] throws an error, the promise returned by `then` gets rejected with the thrown error as its value

So in the below lines:

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/tools/request.js#L72-L80

the first `then()` will get rejected:

```js
module.exports = (route, params) => {
  return wrapFetch(route, params)
    .then(checkStatus)  // <- WILL GET REJECTED with: `new Error(error || 'api_error')`
    .then(parseJSON)
    .catch((err) => {
      throw err;
    });
}
```

***

Additionally, `json()` method will apply two times in below sequence:

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/tools/request.js#L75-L76

first in `checkStatus()` and then in `parseJSON()`:

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/tools/request.js#L17-L32

**Comment by sthielen** [comment]
`request.js` was deprecated in the most recent release
